//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchAPKInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatchAPKInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] adb {
            get {
                object obj = ResourceManager.GetObject("adb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AdbWinApi {
            get {
                object obj = ResourceManager.GetObject("AdbWinApi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select APK Files Path.
        /// </summary>
        internal static string frmMian_cmdOption_Click_Select_APK_Files_Path {
            get {
                return ResourceManager.GetString("frmMian_cmdOption_Click_Select_APK_Files_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Device Connected!.
        /// </summary>
        internal static string frmMian_cmdStart_Click_No_Device_Connected_ {
            get {
                return ResourceManager.GetString("frmMian_cmdStart_Click_No_Device_Connected_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected Software(s)!.
        /// </summary>
        internal static string frmMian_cmdStart_Click_No_selected_Software_s__ {
            get {
                return ResourceManager.GetString("frmMian_cmdStart_Click_No_selected_Software_s__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Connected!.
        /// </summary>
        internal static string frmMian_tmCheck_Tick__Connected_ {
            get {
                return ResourceManager.GetString("frmMian_tmCheck_Tick__Connected_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connect!.
        /// </summary>
        internal static string frmMian_tmCheck_Tick_No_connect_ {
            get {
                return ResourceManager.GetString("frmMian_tmCheck_Tick_No_connect_", resourceCulture);
            }
        }
    }
}
